# ===========================
# Spring Boot Server
# ===========================

server.port=8080

spring.datasource.url=jdbc:mysql://mysql-db:3306/DockerVirtualDB
spring.datasource.username=root
spring.datasource.password=Sujit@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Spring Boot connects to Redis
# using the Redis service name.

spring.data.redis.host=redis-db
spring.data.redis.port=6379